FROM golang:1.25.5 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /hacker-news-clone ./cmd

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM build-stage AS build-release-stage

WORKDIR /

COPY --from=build-stage /hacker-news-clone /hacker-news-clone

EXPOSE 3030

ENTRYPOINT ["/hacker-news-clone"]