// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: post/v1/post.proto

package postv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_post_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *ListPostsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Post struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	NumberOfComments uint64                 `protobuf:"varint,6,opt,name=number_of_comments,json=numberOfComments,proto3" json:"number_of_comments,omitempty"`
	NumberOfUpvotes  uint64                 `protobuf:"varint,7,opt,name=number_of_upvotes,json=numberOfUpvotes,proto3" json:"number_of_upvotes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Post) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Post) GetNumberOfComments() uint64 {
	if x != nil {
		return x.NumberOfComments
	}
	return 0
}

func (x *Post) GetNumberOfUpvotes() uint64 {
	if x != nil {
		return x.NumberOfUpvotes
	}
	return 0
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_post_v1_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{2}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_post_v1_post_proto protoreflect.FileDescriptor

const file_post_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x12post/v1/post.proto\x12\apost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\x10ListPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\x9a\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12,\n" +
	"\x12number_of_comments\x18\x06 \x01(\x04R\x10numberOfComments\x12*\n" +
	"\x11number_of_upvotes\x18\a \x01(\x04R\x0fnumberOfUpvotes\"8\n" +
	"\x11ListPostsResponse\x12#\n" +
	"\x05posts\x18\x01 \x03(\v2\r.post.v1.PostR\x05posts2Q\n" +
	"\vPostService\x12B\n" +
	"\tListPosts\x12\x19.post.v1.ListPostsRequest\x1a\x1a.post.v1.ListPostsResponseB1Z/example.com/authorization/protos/post/v1;postv1b\x06proto3"

var (
	file_post_v1_post_proto_rawDescOnce sync.Once
	file_post_v1_post_proto_rawDescData []byte
)

func file_post_v1_post_proto_rawDescGZIP() []byte {
	file_post_v1_post_proto_rawDescOnce.Do(func() {
		file_post_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_v1_post_proto_rawDesc), len(file_post_v1_post_proto_rawDesc)))
	})
	return file_post_v1_post_proto_rawDescData
}

var file_post_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_post_v1_post_proto_goTypes = []any{
	(*ListPostsRequest)(nil),      // 0: post.v1.ListPostsRequest
	(*Post)(nil),                  // 1: post.v1.Post
	(*ListPostsResponse)(nil),     // 2: post.v1.ListPostsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_post_v1_post_proto_depIdxs = []int32{
	3, // 0: post.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: post.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: post.v1.ListPostsResponse.posts:type_name -> post.v1.Post
	0, // 3: post.v1.PostService.ListPosts:input_type -> post.v1.ListPostsRequest
	2, // 4: post.v1.PostService.ListPosts:output_type -> post.v1.ListPostsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_post_v1_post_proto_init() }
func file_post_v1_post_proto_init() {
	if File_post_v1_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_v1_post_proto_rawDesc), len(file_post_v1_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_v1_post_proto_goTypes,
		DependencyIndexes: file_post_v1_post_proto_depIdxs,
		MessageInfos:      file_post_v1_post_proto_msgTypes,
	}.Build()
	File_post_v1_post_proto = out.File
	file_post_v1_post_proto_goTypes = nil
	file_post_v1_post_proto_depIdxs = nil
}
